config/routes.rb
Rails.application.routes.draw do
  root 'books#index'

  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  get 'sessions/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'signup',   to: 'users#new',        as: 'signup'
  get 'login',    to: 'sessions#new',     as: 'login'
  get 'logout',   to: 'sessions#destroy', as: 'logout'

  resources :books
  resources :authors
  resources :shops, param: :slug
  resources :search, only: [:index]

end

app/models/shop.rb
class Shop < ApplicationRecord
  has_many :books, dependent: :destroy

  validates :name, :slug, presence: true
  validates_uniqueness_of :name, { message: "Name is already taken" }
  validate :uniqueness_of_slug

  before_validation :to_slug

  scope :ordered_by_created_at, -> { order(created_at: :desc) }

  def display_name
    name
  end

  def to_slug
    self.slug = name&.parameterize
  end
  alias_method :to_param, :to_slug

  def uniqueness_of_slug
    if slug_exists?
      errors.add(:name, 'is not unique enough. Maybe this shop already exists?')
    end
  end

  private

  def slug_exists?
    name && Shop.where.not(id: id).exists?(slug: to_slug)
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :require_login, except: [:index, :show]

  def index
    load_shops

    respond_to do |format|
      format.html
      format.json { render json: @shops }
    end
  end

  def new
    build_shop
  end

  def create
    build_shop

    save_shop or render 'new'
  end

  def show
    load_shop
  end

  def edit
    load_shop
    build_shop
  end

  def update
    load_shop
    build_shop

    save_shop or render 'edit'
  end

  def destroy
    load_shop
    @shop.destroy
    redirect_to shops_path, notice: 'Shop was successfully destroyed.'
  end

  private

  def load_shops
    @shops ||= shop_scope.to_a
  end

  def load_shop
    @shop ||= shop_scope.find_by_slug(params[:slug])
  end

  def build_shop
    @shop ||= shop_scope.build
    @shop.attributes = shop_params
  end

  def save_shop
    if @shop.save
      flash[:success] = 'Shop saved.'
      redirect_to shops_path
    end
  end

  def shop_params
    shop_params = params[:shop]
    shop_params ? shop_params.permit(:name) : {}
  end

  def shop_scope
    Shop.ordered_by_created_at.includes(books: :author)
  end
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/shops/_form.html.erb
<div>
  <%= render 'shared/error_messages', object: @shop %>

  <%= form_with model: @shop, local: true do |form| %>
    <%= form.label :name %>
    <%= form.text_field :name %>

    <%= form.submit "Submit" %>
  <% end %>
</div>

app/views/shops/_shop.html.erb
<tr id="<%= shop.id %>">
  <td>
    <span><%= link_to shop.name, shop %></span>
    <%# <input class='input-small hide' type='text' size='30'> %>
  </td>
  <td>
    <div class='float-right btn-group'>
      <%= link_to "Edit", edit_shop_path(shop), class: 'btn btn-warning edit_btn' %>
      <%= link_to "Delete", shop, remote: true, method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-danger delete_btn' %>
    </div>
  </td>
</tr>

app/views/shops/edit.html.erb
<h1>Edit Shop</h1>

<%= render 'form' %>

<%= link_to "Back", shops_path, class: 'btn btn-default' %>

app/views/shops/index.html.erb
<div class='col-md-8 offset-md-2'>
  <h1>Shops</h1>

  <%= link_to "Add shop", new_shop_path, class: 'btn btn-default' %>
  <br>

  <table class='table table-striped table-hover'>
    <thead>
      <tr>
        <th>Name</th>
        <th></th>
      </tr>
    </thead>

    <tbody id="shops">
      <% if @shops.present? %>
        <%= render @shops %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/shops/new.html.erb
<h1>New Shop</h1>

<%= render 'form' %>

<%= link_to "Back", shops_path, class: 'btn btn-default' %>

app/views/shops/show.html.erb
<h1><%= @shop.display_name %></h1>

  <td><%= link_to "Edit", @shop, method: :edit %></td>
  <td><%= link_to "Delete", @shop, method: :delete, data: { confirm: "Are you sure?" } %></td>
</tr>

<h2>Books from this shop:</h2>
<ol>
  <% @shop.books.each do |book| %>
  <li><%= book.title %> (<%= link_to book.author_name, book.author %>)</li>
  <% end %>
</ol>

<br />