config/routes.rb
Rails.application.routes.draw do
  root 'books#index'

  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  get 'sessions/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'signup',   to: 'users#new',        as: 'signup'
  get 'login',    to: 'sessions#new',     as: 'login'
  get 'logout',   to: 'sessions#destroy', as: 'logout'

  resources :books
  resources :authors
  resources :shops, param: :slug
  resources :search, only: [:index]

end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books, dependent: :destroy

  validates :first_name, :last_name, presence: true

  def display_name
    "#{last_name}, #{first_name}"
  end

  def to_param
    "#{id}-#{display_name.parameterize}"
  end
end

app/controllers/api/v1/authors_controller.rb
class Api::V1::AuthorsController < Api::V1::BaseController
  def index
    load_authors
  end

  def create
    load_authors
    build_author

    return api_error(status: :unprocessable_entity, errors: @author.errors) unless @author.valid?

    @author.save
    render(
      json: Api::V1::AuthorSerializer.new(@author).to_json,
      status: :created,
      location: api_v1_author_path(@author.id)
    )
  end

  def show
    load_author

    render(json: Api::V1::AuthorSerializer.new(@author).to_json)
  end

  def update
    load_author
    build_author

    return api_error(status: :unprocessable_entity, errors: @author.errors) unless @author.valid?

    @author.save
    render(
      json: Api::V1::UserSerializer.new(user).to_json,
      status: 200,
      location: api_v1_user_path(user.id),
      serializer: Api::V1::UserSerializer
    )
  end

  def destroy
    load_author

    if !@author.destroy
      return api_error(status: 500)
    end

    head status: 204
  end

  private

  def load_authors
    @authors ||= author_scope.to_a

    render(
      json: ActiveModel::ArraySerializer.new(
        @authors,
        each_serializer: Api::V1::AuthorSerializer,
        root: 'authors',
        meta: meta_attributes(@authors)
      )
    )
  end

  def load_author
    @author ||= author_scope.find(params[:id])
  end

  def build_author
    @author ||= author_scope.build
    @author.attributes = author_params
  end

  def author_params
    author_params = params[:author]
    author_params ? author_params.permit(:first_name, :last_name) : {}
  end

  def author_scope
    Author.all
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :require_login, except: [:index, :show]

  def index
    load_authors

    respond_to do |format|
      format.html
      format.json { render json: @authors }
    end
  end

  def new
    build_author
  end

  def create
    build_author

    save_author or render 'new'
  end

  def show
    load_author
  end

  def edit
    load_author
    build_author
  end

  def update
    load_author
    build_author

    save_author or render 'edit'
  end

  def destroy
    load_author
    @author.destroy
    redirect_to authors_path, notice: 'Author was successfully destroyed.'
  end

  private

  def load_authors
    @authors ||= author_scope.to_a
  end

  def load_author
    @author ||= author_scope.find(params[:id])
  end

  def build_author
    @author ||= author_scope.build
    @author.attributes = author_params
  end

  def save_author
    if @author.save
      flash[:success] = 'Author saved.'
      redirect_to authors_path
    end
  end

  def author_params
    author_params = params[:author]
    author_params ? author_params.permit(:first_name, :last_name) : {}
  end

  def author_scope
    Author.all.includes(:books)
  end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/_author.html.erb
<tr id="<%= author.id %>">
  <td><%= @authors ? @authors.index(author) + 1 : '' %></td>
  <td><%= link_to author.last_name, author %></td>
  <td><%= author.first_name %></td>
  <td><%= link_to "Edit", edit_author_path(author) %></td>
  <td><%= link_to "Delete", author, remote: true, method: :delete, data: { confirm: "Are you sure?" } %></td>
</tr>

app/views/authors/_form.html.erb
<div>
  <%= render 'shared/error_messages', object: @author %>

  <%= form_with model: @author, local: true do |form| %>
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>

    <%= form.submit "Submit" %>
  <% end %>
</div>

app/views/authors/edit.html.erb
<h1>Edit Author</h1>

<%= render 'form' %>

<%= link_to "Back", authors_path, class: 'btn btn-default' %>

app/views/authors/index.html.erb
<h1>Authors</h1>

<%= link_to "Add author", new_author_path, class: 'btn btn-default' %>

<table>
  <thead>
    <tr>
      <th>No.</th>
      <th>Name</th>
      <th>First name</th>
      <th colspan="2">Actions</th>
    </tr>
  </thead>

  <tbody id="authors">
    <%= render @authors %>
  </tbody>
</table>

<br>

app/views/authors/new.html.erb
<h1>New Author</h1>

<%= render 'form' %>

<%= link_to "Back", authors_path, class: 'btn btn-default' %>

app/views/authors/show.html.erb
<h1><%= @author.display_name %></h1>

<table>
  <tbody id="authors">
    <%= render @author %>
  </tbody>
</table>

<h2>Books from this author:</h2>
<ol>
  <% @author.books.each do |book| %>
  <li><%= book.title %> (<%= link_to book.shop_name, book.shop %>)</li>
  <% end %>
</ol>

<br />