config/routes.rb
Rails.application.routes.draw do
  root 'books#index'

  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  get 'sessions/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'signup',   to: 'users#new',        as: 'signup'
  get 'login',    to: 'sessions#new',     as: 'login'
  get 'logout',   to: 'sessions#destroy', as: 'logout'

  resources :books
  resources :authors
  resources :shops, param: :slug
  resources :search, only: [:index]

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="alert alert-danger">
    <h2><%= pluralize(object.errors.count, "error") %> prohibited this from being changed:</h2>

    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %><br />

app/views/shared/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert alert-<%= mapping[type] %>"><%= message %></div><br />
<% end %>

app/views/shared/_header.html.erb
<header class="navbar navbar-expand-lg navbar-fixed-top navbar-inverse navbar-light bg-light">
  <nav class="navbar ">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="navbar-toggler-icon"></span>
    </button> <a class="navbar-brand" href="/">Ebookly</a>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to 'Books', books_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Shops', shops_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Authors', authors_path, class: 'nav-link' %>
        </li>
      </ul>
      <%= form_tag(search_index_path, method: :get, class: 'form-inline') do %>
        <%= text_field_tag :query, params[:query], class: 'form-control mr-sm-2'  %>
        <%= submit_tag 'Search', name: nil, class: 'btn btn-primary my-2 my-sm-0' %>
      <% end %>
    </div>
  </nav>
</header>

app/views/shared/flash_messages.js.erb
$("div.container").prepend("<%= j render(partial: 'shared/flash_messages') %>")